# Generated by Django 2.1.7 on 2019-03-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
